name: COSC 1209 CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  welcome-message:
    name: Welcome Message
    runs-on: ubuntu-latest
    steps:
    - name: Echo Welcome Message
      run: echo "Hi, I am from COSC 1209 class"

  multi-os-build:
    name: Multi-OS Build
    needs: welcome-message
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['17']
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Display OS Information
      run: |
        echo "Running on: ${{ matrix.os }}"
        echo "Java Version: ${{ matrix.java-version }}"
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    
    - name: Display Java Version
      run: java -version

  gradle-build:
    name: Gradle Build and Test
    needs: multi-os-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Update Gradle Wrapper
      run: ./gradlew wrapper --gradle-version=7.6 --no-daemon
    
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
