name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Update Gradle wrapper
      run: |
        sed -i 's/gradle-6.0-bin.zip/gradle-7.6-bin.zip/' gradle/wrapper/gradle-wrapper.properties
        cat gradle/wrapper/gradle-wrapper.properties
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
    - name: Build with Gradle Wrapper
      run: ./gradlew build
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Update Gradle wrapper
      run: |
        sed -i 's/gradle-6.0-bin.zip/gradle-7.6-bin.zip/' gradle/wrapper/gradle-wrapper.properties
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
